name: Deploy to Server

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
        run: |
          # Install SSH agent and configure the key
          sudo apt-get update
          sudo apt-get install -y sshpass
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          
          # Ensure the destination directory exists
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -i private_key -o StrictHostKeyChecking=no "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }}" "mkdir -p ${{ secrets.SERVER_DESTINATION }}"
          
          # Deploy the code
          rsync -e 'sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -i private_key -o StrictHostKeyChecking=no' -avr --exclude ".git/" --exclude ".github/" * "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }}:${{ secrets.SERVER_DESTINATION }}"
          
          # Clean up the private key
          rm -f private_key